FROM node:17.6.0-alpine3.15 as builder

WORKDIR /usr/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder usr/app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]